name: charmed-mysql
base: core22
version: '8.0.43'
summary: MySQL server in a snap.
description: |
  The MySQL software delivers a very fast, multithreaded, multi-user,
  and robust SQL (Structured Query Language) database server. MySQL
  Server is intended for mission-critical, heavy-load production
  systems as well as for embedding into mass-deployed software.

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]
  - build-on: [s390x]
    build-for: [s390x]
grade: stable
confinement: strict
license: Apache-2.0

system-usernames:
  snap_daemon: shared

package-repositories:
  - type: apt
    ppa: data-platform/mysql-shell
  - type: apt
    ppa: data-platform/xtrabackup
  - type: apt
    ppa: data-platform/mysqld-exporter
  - type: apt
    ppa: data-platform/mysqlrouter-exporter
  - type: apt
    ppa: data-platform/percona-server-plugins
  - type: apt
    ppa: data-platform/mysql-pitr-helper

layout:
  /var/lib/mysql-files:
    bind: $SNAP_COMMON/var/lib/mysql-files
  /usr/lib/mysqlrouter:
    symlink: $SNAP/usr/lib/mysqlrouter
  /usr/lib/mysql-router:
    symlink: $SNAP/usr/lib/mysql-router
  /etc/mysqlrouter:
    symlink: $SNAP_DATA/etc/mysqlrouter
  /var/lib/mysqlrouter:
    symlink: $SNAP_DATA/var/lib/mysqlrouter
  /var/log/mysqlrouter:
    symlink: $SNAP_COMMON/var/log/mysqlrouter
  /var/log/mysqlsh:
    bind: $SNAP_COMMON/var/log/mysqlsh
  /usr/lib/mysqlsh:
    bind: $SNAP/lib/mysqlsh
  /etc/nginx:
    bind: $SNAP_DATA/etc/nginx
  /var/lib/nginx:
    bind: $SNAP_COMMON/var/lib/nginx
  /var/log/nginx:
    bind: $SNAP_COMMON/var/log/nginx
  /run/php:
    bind: $SNAP_COMMON/run/php
  /etc/phpmyadmin:
    bind: $SNAP_DATA/etc/phpmyadmin
  /var/lib/phpmyadmin:
    bind: $SNAP_COMMON/var/lib/phpmyadmin

hooks:
  install:
    plugs:
      - network
      - network-bind
  configure:
    plugs:
      - network

slots:
  logs:
    interface: content
    source:
      read:
        - $SNAP_COMMON/var/log/mysql
        - $SNAP_COMMON/var/log/mysqlrouter
  mysqlrouter-sockets:
    interface: content
    content: socket-directory
    write:
      - $SNAP_COMMON/run/mysqlrouter

apps:
  mysql:
    command: usr/bin/mysql
    plugs:
      - network
  mysqld:
    command: start-mysqld.sh
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
  mysqlsh:
    command: run-mysqlsh.sh
    plugs:
      - network
  mysqlbinlog:
    command: usr/bin/mysqlbinlog
  mysql-pitr-helper:
    command: usr/bin/mysql-pitr-helper
    plugs:
      - network
  mysql-pitr-helper-collector:
    command: start-mysql-pitr-helper-collector.sh
    daemon: simple
    install-mode: disable
    restart-delay: 2m
    plugs:
      - network
  mysqlrouter:
    command: run-mysql-router.sh
    plugs:
      - network
  mysqlrouter-service:
    command: start-mysql-router.sh
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
  xtrabackup:
    command: usr/bin/xtrabackup
  xbcloud:
    command: usr/bin/xbcloud
    plugs:
      - network
  xbstream:
    command: usr/bin/xbstream
  mysqld-exporter:
    command: start-mysqld-exporter.sh
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
  mysqlrouter-exporter:
    command: start-mysql-router-exporter.sh
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
  mysqlrouter-passwd:
    command: run-mysql-router-password.sh
  phpmyadmin:
    command: start-phpmyadmin.sh
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind

parts:
  packages-deb:
    plugin: nil
    stage-packages:
      - mysql-server-8.0=8.0.43-0ubuntu0.22.04.2
      - mysql-router=8.0.43-0ubuntu0.22.04.2
      - mysql-shell=8.0.43+dfsg-0ubuntu0.22.04.1~ppa1
      - prometheus-mysqld-exporter=0.14.0-0ubuntu0.22.04.1~ppa3
      - prometheus-mysqlrouter-exporter=5.0.1-0ubuntu0.22.04.1~ppa2
      - percona-xtrabackup=8.0.35-32-0ubuntu0.22.04.1~ppa1
      - mysql-audit-log-filter-plugin=8.0.43+dfsg1-0ubuntu0.22.04.1~ppa1
      - mysql-audit-log-plugin=8.0.43+dfsg1-0ubuntu0.22.04.1~ppa1
      - mysql-auth-ldap-plugin=8.0.43+dfsg1-0ubuntu0.22.04.1~ppa1
      - mysql-binlog-utils-udf-plugin=8.0.43+dfsg1-0ubuntu0.22.04.1~ppa1
      - mysql-pitr-helper=2-0ubuntu0.22.04.1~ppa1
      - util-linux
      - phpmyadmin
      - nginx-light
      - php-fpm
      - php-mysql
      - php-mbstring
      - php-xml
    organize:
      usr/share/doc/mysql-server-8.0/copyright: licenses/COPYRIGHT-mysql-server-8.0
      usr/share/doc/mysql-router/LICENSE.router.gz: licenses/LICENSE-mysql-router
      usr/share/doc/mysqlsh/LICENSE.gz: licenses/LICENSE-mysql-shell
      usr/share/doc/prometheus-mysqld-exporter/copyright: licenses/COPYRIGHT-prometheus-mysqld-exporter
      usr/share/doc/prometheus-mysqlrouter-exporter/copyright: licenses/COPYRIGHT-prometheus-mysqlrouter-exporter
      usr/share/doc/percona-xtrabackup/LICENSE.gz: licenses/LICENSE-percona-xtrabackup
      usr/share/doc/mysql-audit-log-filter-plugin/copyright: licenses/COPYRIGHT-mysql-audit-log-filter-plugin
      usr/share/doc/mysql-audit-log-plugin/copyright: licenses/COPYRIGHT-mysql-audit-log-plugin
      usr/share/doc/mysql-auth-ldap-plugin/copyright: licenses/COPYRIGHT-mysql-auth-ldap-plugin
      usr/share/doc/mysql-binlog-utils-udf-plugin/copyright: licenses/COPYRIGHT-mysql-binlog-utils-udf-plugin
      usr/share/doc/mysql-pitr-helper/copyright: licenses/COPYRIGHT-mysql-pitr-helper
      usr/share/doc/util-linux/copyright: licenses/COPYRIGHT-util-linux
  snap-license:
    plugin: dump
    source: .
    source-type: local
    stage:
      - licenses/LICENSE-snap
    organize:
      LICENSE: licenses/LICENSE-snap
  snap-scripts:
    plugin: dump
    source: snap/local
